name = "Catppuccin Macchiato"
accent_blue = "#8aadf4"
accent_blue_dark = "#7dc4e4"
accent_red = "#ed8796"
accent_red_dark = "#ee99a0"
accent_yellow = "#eed49f"
accent_yellow_dark = "#f0c6c6"
accent_green = "#a6da95"
accent_green_dark = "#8bd5ca"
accent_gray = "#5b6078"
accent_gray_dark = "#494d64"
bg_main = "#24273a"
bg_section = "#1e2030"
bg_hover = "#363a4f"
bg_surface = "#494d64"
bg_head = "#8aadf4"
text_primary = "#cad3f5"
text_secondary = "#b7bdf8"
text_muted = "#a5adcb"
text_light = "#939ab7"
text_contrast = "#24273a"
text_head = "#24273a"
border_light = "#363a4f"
border_hover = "#494d64"