name = "Catppuccin Frappé"
accent_blue = "#8caaee"
accent_blue_dark = "#81c8be"
accent_red = "#e78284"
accent_red_dark = "#ea999c"
accent_yellow = "#e5c890"
accent_yellow_dark = "#eebebe"
accent_green = "#a6d189"
accent_green_dark = "#85c1dc"
accent_gray = "#626880"
accent_gray_dark = "#51576d"
bg_main = "#303446"
bg_section = "#292c3c"
bg_hover = "#414559"
bg_surface = "#51576d"
bg_head = "#8caaee"
text_primary = "#c6d0f5"
text_secondary = "#b5bfe2"
text_muted = "#a5adce"
text_light = "#949cbb"
text_contrast = "#303446"
text_head = "#303446"
border_light = "#414559"
border_hover = "#51576d"