[book]
title = "Kimün"
authors = ["Nico Hormazábal"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/nico2sh/kimun"
edit-url-template = "https://github.com/nico2sh/kimun/edit/main/docs/src/{path}"
default-theme = "kimun"
preferred-dark-theme = "kimun-dark"

[output.html.search]
enable = true
limit-results = 20
use-boolean-and = true
