[book]
title = "Kimün"
authors = []
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/nico2sh/kimun"
edit-url-template = "https://github.com/nico2sh/kimun/edit/main/docs/src/{path}"

[output.html.search]
enable = true
limit-results = 20
use-boolean-and = true
