name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --manifest-path desktop/Cargo.toml
    - name: Run tests core
      run: cargo test --verbose --manifest-path core/Cargo.toml
    - name: Run tests desktop
      run: cargo test --verbose --manifest-path desktop/Cargo.toml
