[package]
name = "notes_desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
notes_core = { path = "../core" }
eframe = { version = "0.30", default-features = false, features = [
  # accesskit struggles with threading
  "default_fonts",
  "wayland",
  "x11",
  "wgpu",
] }
egui_extras = { version = "0.30", features = ["all_loaders", "syntect"] }

rfd = "0.15"

dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

nucleo = "0.5"

log = "0.4"
env_logger = { version = "0.11", default-features = false, features = [
  "auto-color",
  "humantime",
] }
rayon = "1.10"
anyhow = "1.0"
tokio = { version = "1.42", features = ["full"] }
