[application]
name = "Kimün"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Kimün"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.nico2sh"
publisher = "Nico2sh"
